/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ClassicCF(props) {
  const { nodes, materials } = useGLTF('/v2/Classic.Strap.CF.3B/Watches_For_Web_Export.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.29, 1.88, 0]}>
        <mesh geometry={nodes.Plane015.geometry} material={materials.Cartier_Bronze} />
        <mesh geometry={nodes.Plane015_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane015_2.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane015_3.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane015_4.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane015_5.geometry} material={materials.Screws_TitaniumViper} />
      </group>
      <group position={[-0.33, 1.88, 0]}>
        <mesh geometry={nodes.Plane020.geometry} material={materials.Cartier_Bronze} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane020_3.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane020_4.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane020_5.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
      <group position={[0.29, 1.14, 0]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Strap.Jubilee.Bronze']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane001_4.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane001_5.geometry} material={materials.Screws_TitaniumViper} />
      </group>
      <group position={[-0.34, 1.14, 0]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Strap.Jubilee.Bronze']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane011_3.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane011_4.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane011_5.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
      <group position={[-0.33, 0.38, 0]}>
        <mesh geometry={nodes.Plane108.geometry} material={materials['Modern.Strap.SciFi']} />
        <mesh geometry={nodes.Plane108_1.geometry} material={materials['Modern.Strap.Closure.001']} />
        <mesh geometry={nodes.Plane108_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane108_3.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane108_4.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane108_5.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane108_6.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
      <group position={[0.29, 0.38, 0]}>
        <mesh geometry={nodes.Plane104.geometry} material={materials['Modern.Strap.SciFi']} />
        <mesh geometry={nodes.Plane104_1.geometry} material={materials['Modern.Strap.Closure.001']} />
        <mesh geometry={nodes.Plane104_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane104_3.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane104_4.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane104_5.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane104_6.geometry} material={materials.Screws_TitaniumViper} />
      </group>
      <group position={[0.29, -0.39, 0]}>
        <mesh geometry={nodes.Plane031.geometry} material={materials.CS_Black} />
        <mesh geometry={nodes.Plane031_1.geometry} material={materials.Lock_Gold} />
        <mesh geometry={nodes.Plane031_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane031_3.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane031_4.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane031_5.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane031_6.geometry} material={materials.Screws_TitaniumViper} />
      </group>
      <group position={[-0.33, -0.39, 0]}>
        <mesh geometry={nodes.Plane035.geometry} material={materials.CS_Black} />
        <mesh geometry={nodes.Plane035_1.geometry} material={materials.Lock_Gold} />
        <mesh geometry={nodes.Plane035_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane035_3.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane035_4.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane035_5.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane035_6.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
      <group position={[0.29, -1.15, 0]}>
        <mesh geometry={nodes.Plane112.geometry} material={materials['Simple.Strap']} />
        <mesh geometry={nodes.Plane112_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane112_2.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane112_3.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane112_4.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane112_5.geometry} material={materials.Screws_TitaniumViper} />
      </group>
      <group position={[-0.32, -1.15, 0]}>
        <mesh geometry={nodes.Plane113.geometry} material={materials['Simple.Strap']} />
        <mesh geometry={nodes.Plane113_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane113_2.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane113_3.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane113_4.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane113_5.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
      <group position={[-0.32, -1.9, 0]}>
        <mesh geometry={nodes.Plane047.geometry} material={materials.SimpleMetal_Titanium} />
        <mesh geometry={nodes.Plane047_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane047_2.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane047_3.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane047_4.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane047_5.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
      <group position={[0.29, -1.9, 0]}>
        <mesh geometry={nodes.Plane051.geometry} material={materials.SimpleMetal_Titanium} />
        <mesh geometry={nodes.Plane051_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane051_2.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane051_3.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane051_4.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane051_5.geometry} material={materials.Screws_TitaniumViper} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/Classic.Strap.CF.3B/Watches_For_Web_Export.glb')
