/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useTexture, Html } from '@react-three/drei'
import { useLoader } from '@react-three/fiber';
import { TextureLoader } from 'three/src/loaders/TextureLoader';
import { MeshStandardMaterial, RepeatWrapping} from 'three';

export default function ClassicMF({bandColor, backColor, screwColor, ...props}) {
  const { nodes, materials } = useGLTF('/v2/Classic.Strap.MF.3B/Watches_FBX_Export.gltf')

  //Band
  const bandBase = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_BaseColor.jpg')
    bandBase.wrapS = RepeatWrapping
    bandBase.wrapT = RepeatWrapping;
    bandBase.flipY = false;
    bandBase.mapping = RepeatWrapping;

  const bandDisplacement = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Displacement.jpg')
  const bandNormal = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Normal.jpg')
  const bandMetalness = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Metallic.jpg')
  const bandRoughness = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Roughness.jpg')

  //Lock 
  const lockBase = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Lock_BaseColor.jpg')
    lockBase.wrapS = RepeatWrapping
    lockBase.wrapT = RepeatWrapping;
    lockBase.flipY = false;
    lockBase.mapping = RepeatWrapping;

  const lockDisplacement = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Lock_Displacement.jpg')
  const lockNormal = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Lock_Normal.jpg')
  const lockMetalness = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Lock_Metallic.jpg')
  const lockRoughness = useLoader(TextureLoader, '/v2/Classic.Strap.MF.3B/textures/straps/'+bandColor+'/Strap_Lock_Roughness.jpg')
  return (
    <group {...props} dispose={null}>
      <group position={[0.0, 0.0, 0.0]}>
        <mesh geometry={nodes.Plane035.geometry} material={
          new MeshStandardMaterial({
            map: bandBase,
            displacementMap: bandDisplacement,
            normalMap: bandNormal,
            roughnessMap: bandRoughness,
            metalnessMap: bandMetalness,
            metalness: true,
            roughness: true,
            displacementScale: 0
          })
        } />
        <mesh geometry={nodes.Plane035_1.geometry} material={
          new MeshStandardMaterial({
            map: lockBase,
            displacementMap: lockDisplacement,
            normalMap: lockNormal,
            roughnessMap: lockRoughness,
            metalnessMap: lockMetalness,
            metalness: true,
            roughness: true,
            displacementScale: 0
          })
        } />
        <mesh geometry={nodes.Plane035_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane035_3.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane035_4.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane035_5.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane035_6.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/Classic.Strap.MF.3B/Watches_FBX_Export.gltf')
