/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function JubileeMF(props) {
  const { nodes, materials } = useGLTF('/v2/Jubilee.Strap.MF.3B/Watches_FBX_Export.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.0, 0.0, 0.0]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Strap.Jubilee.Bronze']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane011_3.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane011_4.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane011_5.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/Jubilee.Strap.MF.3B/Watches_FBX_Export.gltf')
