/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModernCF(props) {
  const { nodes, materials } = useGLTF('/v2/Modern.Strap.CF.3B/Watches_FBX_Export.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.0, 0.0, 0.0]}>
        <mesh geometry={nodes.Plane104.geometry} material={materials['Modern.Strap.SciFi']} />
        <mesh geometry={nodes.Plane104_1.geometry} material={materials['Modern.Strap.Closure.001']} />
        <mesh geometry={nodes.Plane104_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane104_3.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane104_4.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane104_5.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane104_6.geometry} material={materials.Screws_TitaniumViper} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/Modern.Strap.CF.3B/Watches_FBX_Export.gltf')
