/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SimpleMCF(props) {
  const { nodes, materials } = useGLTF('/v2/Simple.Metal.Strap.CF.3B/Watches_FBX_Export.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.0, 0.0, 0.0]}>
        <mesh geometry={nodes.Plane051.geometry} material={materials.SimpleMetal_Titanium} />
        <mesh geometry={nodes.Plane051_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane051_2.geometry} material={materials['Display.006']} />
        <mesh geometry={nodes.Plane051_3.geometry} material={materials.Front_Titanium_Viper} />
        <mesh geometry={nodes.Plane051_4.geometry} material={materials.Back_Titanium} />
        <mesh geometry={nodes.Plane051_5.geometry} material={materials.Screws_TitaniumViper} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/Simple.Metal.Strap.CF.3B/Watches_FBX_Export.gltf')
