/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SimpleMF(props) {
  const { nodes, materials } = useGLTF('/v2/Simple.Strap.MF.3B/Watches_FBX_Export.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.0, 0.0, 0.0]}>
        <mesh geometry={nodes.Plane113.geometry} material={materials['Simple.Strap']} />
        <mesh geometry={nodes.Plane113_1.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane113_2.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane113_3.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane113_4.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane113_5.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/Simple.Strap.MF.3B/Watches_FBX_Export.gltf')
