/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useLoader } from '@react-three/fiber';
import { TextureLoader } from 'three/src/loaders/TextureLoader';
import { MeshStandardMaterial } from 'three';

export default function Cartier(props) {
  const { nodes, materials } = useGLTF('/v2/cartier/3watch.glb')

  const copper = useTexture({
    map: '/txt/Jubilee/Copper/Strap_BaseColor.jpg',
    displacementMap: '/txt/Jubilee/Copper/Strap_Displacement.jpg',
    normalMap: '/txt/Jubilee/Copper/Strap_Normal.jpg',
    roughnessMap: '/txt/Jubilee/Copper/Strap_Roughness.jpg'
  })

  const middle = useTexture({
    map: '/txt/Jubilee/Middle/Rose_Gold/Face_Middle_BaseColor.jpg',
    displacementMap: '/txt/Jubilee/Middle/Rose_Gold/Face_Middle_Displacement.jpg',
    normalMap: '/txt/Jubilee/Middle/Rose_Gold/Face_Middle_Normal.jpg',
    roughnessMap: '/txt/Jubilee/Middle/Rose_Gold/Face_Middle_Roughness.jpg'
  })
  

  const [colorMap, displacementMap, normalMap, roughnessMap] = useLoader(TextureLoader, [
    '/txt/Cartier/Titanium/Strap_BaseColor.jpg',
    '/txt/Cartier/Titanium/Strap_Displacement.jpg',
    '/txt/Cartier/Titanium/Strap_Normal.jpg',
    '/txt/Cartier/Titanium/Strap_Roughness.jpg',
  ])

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>


        <mesh geometry={nodes.Plane020.geometry} 
        
        >
            <meshStandardMaterial
            displacementScale={0.0}
            map={colorMap} 
            displacementMap={displacementMap}
            normalMap={normalMap}
            roughnessMap={roughnessMap}
            />

        </mesh>
        <mesh geometry={nodes.Plane020_1.geometry} material={materials['Face_Middle.Bronze.002']} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials['Display.002']} />
        <mesh geometry={nodes.Plane020_3.geometry} material={materials['Face_RubbyWhite.002']} />
        <mesh geometry={nodes.Plane020_4.geometry} material={materials['Screws_Titanium.002']} />
        <mesh geometry={nodes.Plane020_5.geometry} material={materials['Back_.CarbonGreen.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/cartier/3watch.glb')
