/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/v2/modern/Watches_FBX_Export.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh geometry={nodes.Plane108.geometry} material={materials['Modern.Strap.SciFi']} />
        <mesh geometry={nodes.Plane108_1.geometry} material={materials['Modern.Strap.Closure.001']} />
        <mesh geometry={nodes.Plane108_2.geometry} material={materials['Face_Middle.Bronze']} />
        <mesh geometry={nodes.Plane108_3.geometry} material={materials['Display.005']} />
        <mesh geometry={nodes.Plane108_4.geometry} material={materials['Face_RubbyWhite.004']} />
        <mesh geometry={nodes.Plane108_5.geometry} material={materials.Screws_Titanium} />
        <mesh geometry={nodes.Plane108_6.geometry} material={materials['Back_.CarbonGreen']} />
      </group>
    </group>
  )
}

useGLTF.preload('/v2/modern/Watches_FBX_Export.gltf')
